package com.leetcode;

public class _389_Find_the_Difference {


/*

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"
*/

    public char findTheDifference(String s, String t) {

        int[] letters = new int[26];
        int min = Math.min(s.length(), t.length());

        for (int i = 0; i < min; i++) {
            int a = s.charAt(i) - 'a';
            int b = t.charAt(i) - 'a';
            letters[a] = letters[a] + 1;
            letters[b] = letters[b] - 1;
        }

        letters[t.charAt(t.length() - 1) - 'a'] = letters[t.charAt(t.length() - 1) - 'a'] - 1;

        for (int i = 0; i < letters.length; i++) {
            if (letters[i] != 0) {
                return (char) (i + 'a');
            }
        }

        return ' ';
    }


}
